server:
  port: 8000
spring:
  application:
    name: api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-test-query: select 1 from dual
  redis:
    cluster:
      nodes: 192.168.27.202:7000,192.168.27.202:7001,192.168.27.202:7002,192.168.27.203:7003,192.168.27.203:7004,192.168.27.203:7005
#    password: qwert@1Qaz